language: c

jobs:
  include:
  - compiler: clang
    os: linux
    addons:
      apt:
        packages:
        - libiodbc2-dev
    env:
      - CONFIGURE_FLAGS=--with-iodbc=/usr
  - compiler: clang
    os: linux
    addons:
      apt:
        packages:
        - unixodbc-dev
    env:
      - CONFIGURE_FLAGS=--with-unixodbc=/usr
  - compiler: gcc
    os: linux
    addons:
      apt:
        packages:
        - libiodbc2-dev
    env:
      - CONFIGURE_FLAGS=--with-iodbc=/usr
  - compiler: gcc
    os: linux
    addons:
      apt:
        packages:
        - unixodbc-dev
    env:
      - CONFIGURE_FLAGS=--with-unixodbc=/usr
  - compiler: clang
    os: osx
    osx_image: xcode11.4
    addons:
      homebrew:
        packages:
        - libiodbc
    env:
      - CONFIGURE_FLAGS=--with-iodbc=/usr/local/opt
  - compiler: clang
    os: osx
    osx_image: xcode11.4
    addons:
      homebrew:
        packages:
        - unixodbc
    env:
      - CONFIGURE_FLAGS=--with-unixodbc=/usr/local/opt
  - compiler: gcc
    os: osx
    osx_image: xcode11.4
    addons:
      homebrew:
        packages:
        - libiodbc
    env:
      - CONFIGURE_FLAGS=--with-iodbc=/usr/local/opt
  - compiler: gcc
    os: osx
    osx_image: xcode11.4
    addons:
      homebrew:
        packages:
        - unixodbc
    env:
      - CONFIGURE_FLAGS=--with-unixodbc=/usr/local/opt

before_script:
  - autoreconf -i -f -Wno-portability

script:
  - ./configure --disable-man --disable-silent-rules --disable-glib $CONFIGURE_FLAGS
  - make
  - ./src/util/mdb-array test/data/ASampleDatabase.accdb "Asset Items"
  - ./src/util/mdb-array test/data/nwind.mdb "Customers"
  - ./src/util/mdb-count test/data/ASampleDatabase.accdb "Asset Items"
  - ./src/util/mdb-count test/data/nwind.mdb "Customers"
  - ./src/util/mdb-prop test/data/ASampleDatabase.accdb "Asset Items"
  - ./src/util/mdb-prop test/data/nwind.mdb "Customers"
  - ./src/util/mdb-schema test/data/ASampleDatabase.accdb
  - ./src/util/mdb-schema test/data/nwind.mdb
  - ./src/util/mdb-tables test/data/ASampleDatabase.accdb
  - ./src/util/mdb-tables test/data/nwind.mdb
  - ./src/util/mdb-ver test/data/ASampleDatabase.accdb
  - ./src/util/mdb-ver test/data/nwind.mdb
  - env MDBPATH=test/data ./src/odbc/unittest
